# Generated by Django 6.0.2 on 2026-02-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('OAK', 'Oak'), ('PINE', 'Pine'), ('MAPLE', 'Maple'), ('WALNUT', 'Walnut'), ('CHERRY', 'Cherry'), ('OTHER', 'Other')], max_length=50)),
                ('grade', models.CharField(choices=[('FAS', 'FAS (Firsts and Seconds)'), ('SELECT', 'Select'), ('NO1_COMMON', 'No. 1 Common'), ('NO2_COMMON', 'No. 2 Common'), ('STUD', 'Stud'), ('OTHER', 'Other')], max_length=50)),
                ('dimensions', models.CharField(help_text='e.g. 2x4x8', max_length=100)),
                ('moisture_content', models.FloatField(help_text='Percentage (e.g. 12.5)')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SawmillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('location', models.CharField(help_text='e.g. 123 Timber Rd, Portland, OR', max_length=255)),
                ('machinery_details', models.TextField(blank=True, help_text='List equipment like band saws, kilns, etc.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sawmill_logos/')),
            ],
        ),
    ]
